### DISCUSSION TITLE
Slider marks and steps

### DISCUSSION THREAD

**Discussion by PiousVenom** [rsuite/rsuite#2059] [Q&A]
Is it possible to specify ticks at specific irregular intervals? For instance, I want to build a slider with min of .5 and max of 2, but I want ticks at .5, .66, .84, 1, 1.33, 1.66, and 2. Is that doable?

**Comment by simonguo** [comment]
If you just want to highlight a specific value, you can customize it with `renderMark`.

```tsx
<Slider
  step={0.01}
  graduated
  progress
  min={0.5}
  max={2}
  renderMark={mark => {
    if ([0.5, 0.66, 0.84, 1, 1.33, 1.66].includes(mark)) {
      return <span>{mark}</span>;
    }
    return null;
  }}
/>
```

Use css to hide the dense dots.

```css
.rs-slider-graduator>ul>li:before, .rs-slider-graduator>ul>li:last-child:after{
  display: none;
}
```
