### DISCUSSION TITLE
Manipulating components using scss modules

### DISCUSSION THREAD

**Discussion by avifatal** [rsuite/rsuite#2242] [General]
Hi,
i want to change a certain Table inner padding size.
So in my component.module.scss I added this:

```scss
.transactionList {
  & .rs-table-cell-content{
     padding: 2px;
  }
}
```
This doesnt has any effect on the table.
Thanks
