### DISCUSSION TITLE
How to change rows color in table in different status

### DISCUSSION THREAD

**Discussion by calvin1012** [rsuite/rsuite#2377] [Q&A] [answered]
Same as title, did anyone have idea?

**Comment by simonguo** [comment, marked as answer]
Use `rowClassName` to set a custom `className` for a row

```tsx
<Table
  rowClassName={(rowData) =>{
     //  Returns a different className by judging the current row index.
     return 'my-table-row'
  }}
>
```

```css
.my-table-row, .my-table-row .rs-table-cell {
    background: red;
}
```
