### DISCUSSION TITLE
Center the modal vertically

### DISCUSSION THREAD

**Discussion by RamonPessoa** [rsuite/rsuite#2485] [Q&A] [answered]
Hey guys, i'm new to rsuite and I couldn't figure out how to center align vertically the modal dialog box, does anyone have any idea about how to do that?

**Comment by simonguo** [comment, marked as answer]
hi @RamonPessoa 

The Model component currently does not have a corresponding property to support it. But you can add css code to the Model container to meet the requirements.

```css
.rs-modal-wrapper{
  display: flex;
  align-items: center;
}
```
