### DISCUSSION TITLE
Table word wrap

### DISCUSSION THREAD

**Discussion by randerson57261** [rsuite/rsuite#2544] [Q&A]
Can the table be controlled to wrap words (breaking at spaces)?

![image](https://user-images.githubusercontent.com/74583143/173662285-78b639aa-1d43-47bc-8a03-c017cdc860dd.png)

Currently adding "wordWrap" to Table splits words.

**Comment by simonguo** [comment]
Hi  @randerson57261
 
At present, the text overflow in the table will force wrap word, which is really unfriendly from the experience, and we will adjust it as soon as possible.

If you're in a hurry, you can satisfy your needs with the following CSS overrides.

```css
.rs-table-word-wrap .rs-table-cell-content{
  white-space: normal;
  word-break: break-word;
}
```
