### DISCUSSION TITLE
縮減Form 兩個InputFeild 之間的上下距離

### DISCUSSION THREAD

**Discussion by calvin1012** [rsuite/rsuite#2736] [Q&A] [answered]
和標題一樣, 如何在垂直佈局下縮減上下距離?
![image](https://user-images.githubusercontent.com/86409748/191220999-195f149b-cf83-485a-8a02-ff8e8ba40c03.png)

**Comment by simonguo** [comment, marked as answer]
目前没有对应的 props 进行调整，可以通过以下方式解决你的问题。

- less 变量修改 (推荐) ，参考文档: https://rsuitejs.com/guide/customization/

```less
@form-group-margin-bottom: 14px; // default 24px
```

- 或者 css 样式覆盖

```css
.rs-form-group {
  margin-bottom: 14px !important;
}
```
