### DISCUSSION TITLE
How to create custom colors that changes accordsing to active theme

### DISCUSSION THREAD

**Discussion by Deccoyi** [rsuite/rsuite#2996] [Q&A] [answered]
Hi I am using CustomProvider to switch between dark/light themes. I also have a custom .less file. I want to use colors that are **not standard rsuite colors** and I want them to change according to theme? Is there a proper way to do this?

```less
.myLink {
     &:not(.active) {
          background-color: transparent;
      }
     &.active {
          background-color: @B700-dark;
      }
```

If I do it like above obviously it doesnt change.

```json
  "dependencies": {
    "@rsuite/icons": "^1.0.2",
    "less": "^4.1.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.7.1",
    "react-router-dom": "^6.6.1",
    "rsuite": "^5.23.3"
  },
```

Edit:

Oops. I realized `<body> `tag has a class based on theme. Thank you guys tho.

**Comment by simonguo** [comment, marked as answer]
Hi @Deccoyi  You can customize the color of the component by modifying the less variable. It is detailed in the documentation: https://rsuitejs.com/guide/customization/

**Reply by Deccoyi** [reply]
**Thank you** I wanted to use rsuite colors for my custom classes. Maybe adding an example like this in the documentation may help others.

```less
.rs-theme-dark {
     .myCustomDiv {
          background-color: @B800-dark;
     }
}

.rs-theme-light {
     .myCustomDiv {
          background-color: @B200;
     }
}
```
