### DISCUSSION TITLE
Unique styles for each component

### DISCUSSION THREAD

**Discussion by jeremystewart21** [rsuite/rsuite#3240] [Q&A]
Hi Guys
Wondering if someone can help point me in the right direction. I am trying to use the SelectPicker in two different place in my site for two different purposes.

I need to style each one independently of each other and I just cannot figure out how to do it! It is a NextJS/React website (plus Tailwind) - I just need to scope seperate styles.

**Comment by SevenOutman** [comment]
Hi @jeremystewart21, one approach is to create two separate CSS classes with wanted styles and assign them to the two SelectPickers accordingly.

```css
.red-select-picker {
  color: red;
}

.green-select-picker {
  color: green;
}
```

```jsx
<SelectPicker className="red-select-picker" />
<SelectPicker className="green-select-picker" />
```

**Reply by jeremystewart21** [reply]
Hey, thanks for the answer. I think we might have tried this approach. How about this one. In one dropdown list the links are aligned left and for another the links are aligned right?

**Reply by SevenOutman** [reply]
If I understand correctly it's the same solution

```css
.left-dropdown-item {
  text-align: left;
}

.right-dropdown-item {
  text-align: right;
}
```

```jsx
<Dropdown>
  <Dropdown.Item className="left-dropdown-item">Left aligned</Dropdown.Item>
</Dropdown>

<Dropdown>
  <Dropdown.Item className="right-dropdown-item">Right aligned</Dropdown.Item>
</Dropdown>
```
