### ISSUE TITLE
Icon 支持 fillColor 属性

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#1000]
### What problem does this feature solve?

`<Icon/>` 支持使用 svg ，但是颜色现在需要自己写一个 `.fill-color` 
``` css
.fill-color use{
    fill: currentColor;
}
``` 

感觉使用起来不是很方便。确实，考虑到彩色图标不能让 svg 的颜色使用继承字体颜色。但是感觉可以让他是个配置项。这样用起来就很方便了。

### What does the proposed API look like?

```jsx
<Icon icon={SvgIcons.Search} fillColor />
```
