### ISSUE TITLE
Table rowClassName not sopport background 【BUG】

### ISSUE THREAD

**Issue by VirgoArt** [rsuite/rsuite#1012]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `lastest` |

i want to set a row background when i click it, but i got right classname on row class, howevery
rowClassName set color style is ok, but background is not work

**Comment by simonguo** [comment]
I guess you may want to modify the background of the `cell`.
```tsx
<Table rowClassName="active-row">
```
```css
.active-row .rs-table-cell {
    background: red;
}
```
