### ISSUE TITLE
Drawer backdrop click for close doesn't work

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#2258]
### What version of rsuite are you using?

5

### What version of React are you using?

17

### What browser are you using?

chrome

### Describe the Bug

https://next.rsuitejs.com/components/drawer/
earlier, pressing the background area would close the popup

now, this functionality is gone

### To Reproduce

https://next.rsuitejs.com/components/drawer/

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2259. 
Will be released this week,  you can temporarily solve the problem with a CSS rewrite.

```css
.rs-drawer-wrapper {
    z-index: 1050;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```
