### ISSUE TITLE
enforceStatus on Drawer component not working

### ISSUE THREAD

**Issue by raibikys** [rsuite/rsuite#2303]
### What version of rsuite are you using?

5.4.4 same on 5.5.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.2

### What browser are you using?

Chrome

### Describe the Bug

With enforceStatus={false} clicking outside drawer should be allowed. Now other elements, outside drawer bounds can't be selected.

### To Reproduce

https://codesandbox.io/s/reverent-fermi-84bmj

**Comment by simonguo** [comment]
Hi @raibikys  you should use `enforceFocus` instead of `enforceStatus`.

If you want the element behind the `drawer` to be interactive, you can add the following CSS to work around it.
```css
:not(.rs-drawer-has-backdrop) .rs-drawer-wrapper {
  width: 0;
  height: 0;
}
```
