### ISSUE TITLE
Rsuite default style import overrides my app styles

### ISSUE THREAD

**Issue by RoseannePeeters** [rsuite/rsuite#3513]
### What version of rsuite are you using?

^5.48.0

### What version of React are you using?

18

### What version of TypeScript are you using (if any)?

/

### What browser are you using?

The Grand Firefox

### Describe the Bug

This issue is referring to: https://github.com/rsuite/rsuite/issues/1953
On that post @Jefferson-Butler1 also described having issues but is was closed already.

I make a new one because it is closed.
While for some people it fixes by doing:
`import "rsuite/dist/rsuite-no-reset.min.css";`
instead of
`import 'rsuite/dist/rsuite.min.css';`

For me it doesn't, it is still messing with my css.
For example it is adding box-sizing: border-box; which is messing some of my styling up.
How can I prevent this? I want scoped css or css limited per component.
I tried scoping css or using css modules but you are using imports inside the css

I would also like to have the css per component so not all my pages which do not have components have all those css vars.

### Expected Behavior

when importing the default rsuite styles the body of my App don't need to override,

### Currently I can fix it in a bad way with following css:
```css
body{
    -webkit-font-smoothing: initial !important;
    -moz-osx-font-smoothing: initial !important;
}
*, ::after, ::before{
        box-sizing:content-box !important 
}
```
Why is this a bad way?
Your components use box-sizing so it messes up the components.
Secondly:
I still have all the css in all my pages while I only use 2 components in one page. I don't like this, is there a way to only have the css of the components or limit it to 1 page?
