### ISSUE TITLE
Allow adjusting Animation Fade transition time

### ISSUE THREAD

**Issue by jasperfirecai2** [rsuite/rsuite#3970]
### What problem does this feature solve?

I've been trying to use Animation.Fade to easy the transition from fallback to loaded component in suspend boundaries. However, the animation is a bit too fast for my purposes. I checked the docs for css variables and the source index.css file but it doesn't look like the value is configurable. I know i can override the css myself with a css selector, but i think it would be a meaningful feature to be able to edit the transition time using css vars and/or props in the component.

### What does the proposed API look like?

```css
--rs-anim-fade-duration: 0.15s

.rs-anim-fade {
  opacity: 0;
  -webkit-transition: opacity var(--rs-animation-fade-duration) linear;
  transition: opacity var(--rs-animation-fade-duration) linear;
  pointer-events: none;
}
```
or 
```jsx
<Animation.Fade duration={150}>
 <div></div>
</Animation.Fade>
```
Although for simple implementation i think the css var approach makes more sense
