### ISSUE TITLE
CheckTreeComponent Animation

### ISSUE THREAD

**Issue by bennihoss** [rsuite/rsuite#635]
### feature request,:
Could it be possible to animate the CheckTree Component via config, it would need the Collapse-Component for the ".rs-check-tree-children".  

### What is the expected behavior?
Collapsing animation between tree-open and tree-closed states.

### What is the current behavior?
No animation, switch between by display:block & display:none

I tried to animate them with css, but there is no proper way to animate those, if the tree-height is set to auto. Would be a nice feature, i'm using the CheckTree Component inside another collapsing component and it doesn't feed good with that static transition.

**Comment by simonguo** [comment]
In the case of too many tree nodes, the animation will result in unsmooth operation and affect normal use. So we gave up the animation effect.

**Comment by bennihoss** [comment]
Hm okay, i currently animate the tree by css, it works smooth on desktop and newer smartphones, but my tree nodes count is currently only between 20-30. My problem is, because of the animation of max height, i have a max-height that i don't want and there are some  lags when closing a small tree, because it animates 700px and not only the 50px like it should. When i want a animation of the real height, i will need javascript for that. 

```scss

.rs-check-tree-node-children {
	& > .rs-check-tree-children {
		display: block;
		max-height: 0;
		transition: max-height 0.3s ease-in-out;
		overflow: hidden;
	}
	& .rs-check-tree-open {
		& > .rs-check-tree-children {
			display: block;
			max-height: 700px;
		}
	}
}

```


Sadly without the animation the tree seems so static and unresponsive, it doesn't fit into our site that well, so i would like to keep the animation. If i would make a pull request with that animation configuration optionally, would you accept it or does your guideline decline such "experimantal" configs that could restrict the UX? The documentation would need a mark that this feature should only be used on small trees.

If not, no problem, then i will have to check if i implement my own check tree compnent or live with the limitations ;)
