### ISSUE TITLE
How can I change the background color of day cell?

### ISSUE THREAD

**Issue by yuliakal** [rsuite/rsuite#844]
I can render custom cell through `renderCell()` props. However I want to change whole background of `rs-calendar-table-cell` and I'm not able to find appropriate less variable or way to change.
The cell here I mean is that include label of `day`.

**Comment by simonguo** [comment]
I think that to solve your custom needs can be overridden by css style.
```tsx
<Calendar className="custom-calendar" />
```

```css
.custom-calendar .rs-calendar-table-cell{
    background: red;
}
```
